import { SongDataProps } from "./types";

export const musicDataMock: SongDataProps[] = [
  {
    song: "Dark Fantasy",
    duration: "5:12",
    artist: "Kanye West",
    album: "My Beautiful Dark Twisted Fantasy",
    cover: "unreleased_cover.png",
  },
  {
    song: "Power",
    duration: "4:52",
    artist: "Kanye West",
    album: "My Beautiful Dark Twisted Fantasy",
    cover: "unreleased_cover.png",
  },
  {
    song: "Runaway",
    duration: "3:46",
    artist: "Kanye West",
    album: "My Beautiful Dark Twisted Fantasy",
    cover: "unreleased_cover.png",
  },
  {
    song: "Devil in a New Dress",
    duration: "5:52",
    artist: "Kanye West",
    album: "My Beautiful Dark Twisted Fantasy",
    cover: "unreleased_cover.png",
  },
  {
    song: "Blame Game",
    duration: "7:49",
    artist: "Kanye West",
    album: "My Beautiful Dark Twisted Fantasy",
    cover: "unreleased_cover.png",
  },
  {
    song: "Monster",
    duration: "6:18",
    artist: "Kanye West",
    album: "My Beautiful Dark Twisted Fantasy",
    cover: "unreleased_cover.png",
  },
  {
    song: "Who Will Survive in America",
    duration: "1:38",
    artist: "Kanye West",
    album: "My Beautiful Dark Twisted Fantasy",
    cover: "cover.png",
  },
  {
    song: "See Me Now",
    duration: "6:03",
    artist: "Kanye West",
    album: "My Beautiful Dark Twisted Fantasy",
    cover: "cover.png",
  },
  {
    song: "Gorgeous",
    duration: "5:57",
    artist: "Kanye West",
    album: "My Beautiful Dark Twisted Fantasy",
    cover: "cover.png",
  },
  {
    song: "All of the lights",
    duration: "2:54",
    artist: "Kanye West",
    album: "My Beautiful Dark Twisted Fantasy",
    cover: "cover.png",
  },
  {
    song: "So Appalled",
    duration: "3:51",
    artist: "Kanye West",
    album: "My Beautiful Dark Twisted Fantasy",
    cover: "cover-1.png",
  },
  {
    song: "Livin' In A Movie",
    duration: "3:27",
    artist: "Kanye West",
    album: "Freshmen Adustment",
    cover: "cover-1.png",
  },
  {
    song: "Ok Ok",
    duration: "3:25",
    artist: "Kanye West",
    album: "Donda",
    cover: "cover-1.png",
  },
  {
    song: "Donda",
    duration: "2:08",
    artist: "Kanye West",
    album: "Donda",
    cover: "cover-1.png",
  },
  {
    song: "Hold Up",
    duration: "3:42",
    artist: "Beyonce",
    album: "Lemonade",
    cover: "cover-1.png",
  },
];
