import { SongDataProps } from "./types";

export const musicDataMock: SongDataProps[] = [
  {
    song: "Dark Fantasy",
    duration: "312",
    artist: "Kanye West",
    album: "My Beautiful Dark Twisted Fantasy",
    cover: "unreleased_cover.png",
  },
  {
    song: "Power",
    duration: "292",
    artist: "Kanye West",
    album: "My Beautiful Dark Twisted Fantasy",
    cover: "cover.png",
  },
  {
    song: "Runaway",
    duration: "354",
    artist: "Kanye West",
    album: "My Beautiful Dark Twisted Fantasy",
    cover: "unreleased_cover.png",
  },
  {
    song: "Devil in a New Dress",
    duration: "234",
    artist: "Kanye West",
    album: "My Beautiful Dark Twisted Fantasy",
    cover: "unreleased_cover.png",
  },
  {
    song: "Blame Game",
    duration: "532",
    artist: "Kanye West",
    album: "My Beautiful Dark Twisted Fantasy",
    cover: "unreleased_cover.png",
  },
  {
    song: "Monster",
    duration: "490",
    artist: "Kanye West",
    album: "My Beautiful Dark Twisted Fantasy",
    cover: "unreleased_cover.png",
  },
  {
    song: "Who Will Survive in America",
    duration: "87",
    artist: "Kanye West",
    album: "My Beautiful Dark Twisted Fantasy",
    cover: "cover.png",
  },
  {
    song: "See Me Now",
    duration: "341",
    artist: "Kanye West",
    album: "My Beautiful Dark Twisted Fantasy",
    cover: "cover.png",
  },
  {
    song: "Gorgeous",
    duration: "532",
    artist: "Kanye West",
    album: "My Beautiful Dark Twisted Fantasy",
    cover: "cover.png",
  },
  {
    song: "All of the lights",
    duration: "215",
    artist: "Kanye West",
    album: "My Beautiful Dark Twisted Fantasy",
    cover: "cover.png",
  },
  {
    song: "So Appalled",
    duration: "128",
    artist: "Kanye West",
    album: "My Beautiful Dark Twisted Fantasy",
    cover: "cover-1.png",
  },
  {
    song: "Livin' In A Movie",
    duration: "162",
    artist: "Kanye West",
    album: "Freshmen Adustment",
    cover: "cover-1.png",
  },
  {
    song: "Ok Ok",
    duration: "294",
    artist: "Kanye West",
    album: "Donda",
    cover: "cover-1.png",
  },
  {
    song: "Donda",
    duration: "208",
    artist: "Kanye West",
    album: "Donda",
    cover: "cover-1.png",
  },
  {
    song: "Hold Up",
    duration: "242",
    artist: "Beyonce",
    album: "Lemonade",
    cover: "cover-1.png",
  },
];
